spring:
  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: #不设置密码
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://cloud-gateway:8201/cloud-auth/rsa/publicKey'
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.yizhou.cloud: info
logstash:
  host: logstash