spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    root: info
    com.yizhou.cloud: debug
logstash:
  host: localhost