version: '3'
services:
  cloud-admin:
    image: cloud/cloud-admin:1.0-SNAPSHOT
    container_name: cloud-admin
    ports:
      - 8080:8080
    volumes:
      - /home/app/cloud-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - mysql:db #可以用db这个域名访问mysql服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  cloud-search:
    image: cloud/cloud-search:1.0-SNAPSHOT
    container_name: cloud-search
    ports:
      - 8081:8081
    volumes:
      - /home/app/cloud-search/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
      - mysql:db #可以用db这个域名访问mysql服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  cloud-portal:
    image: cloud/cloud-portal:1.0-SNAPSHOT
    container_name: cloud-portal
    ports:
      - 8085:8085
    volumes:
      - /home/app/cloud-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - mongo:mongo #可以用mongo这个域名访问mongo服务
      - mysql:db #可以用db这个域名访问mysql服务
      - rabbitmq:rabbit #可以用rabbit这个域名访问rabbitmq服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  cloud-auth:
    image: cloud/cloud-auth:1.0-SNAPSHOT
    container_name: cloud-auth
    ports:
      - 8401:8401
    volumes:
      - /home/app/cloud-auth/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  cloud-gateway:
    image: cloud/cloud-gateway:1.0-SNAPSHOT
    container_name: cloud-gateway
    ports:
      - 8201:8201
    volumes:
      - /home/app/cloud-gateway/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - redis:redis #可以用redis这个域名访问redis服务
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务
  cloud-monitor:
    image: cloud/cloud-monitor:1.0-SNAPSHOT
    container_name: cloud-monitor
    ports:
      - 8101:8101
    volumes:
      - /home/app/cloud-monitor/logs:/var/logs
      - /etc/localtime:/etc/localtime
    environment:
      - 'TZ="Asia/Shanghai"'
    external_links:
      - nacos-registry:nacos-registry #可以用nacos-registry这个域名访问nacos服务