server:
  port: 8201
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: cloud-auth
          uri: lb://cloud-auth
          predicates:
            - Path=/cloud-auth/**
          filters:
            - StripPrefix=1
        - id: cloud-admin
          uri: lb://cloud-admin
          predicates:
            - Path=/cloud-admin/**
          filters:
            - StripPrefix=1
        - id: cloud-portal
          uri: lb://cloud-portal
          predicates:
            - Path=/cloud-portal/**
          filters:
            - StripPrefix=1
        - id: cloud-search
          uri: lb://cloud-search
          predicates:
            - Path=/cloud-search/**
          filters:
            - StripPrefix=1
        - id: cloud-demo
          uri: lb://cloud-demo
          predicates:
            - Path=/cloud-demo/**
          filters:
            - StripPrefix=1
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/cloud-auth/oauth/token"
      - "/cloud-auth/rsa/publicKey"
      - "/cloud-search/**"
      - "/cloud-portal/sso/login"
      - "/cloud-portal/sso/register"
      - "/cloud-portal/sso/getAuthCode"
      - "/cloud-portal/home/**"
      - "/cloud-portal/product/**"
      - "/cloud-portal/brand/**"
      - "/cloud-admin/admin/login"
      - "/cloud-admin/admin/register"
      - "/cloud-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
