spring:
  datasource:
    url: jdbc:mysql://db:3306/cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: mongo
      port: 27017
      database: cloud-port
  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  rabbitmq:
    host: rabbit
    port: 5672
    virtual-host: /cloud
    username: cloud
    password: cloud
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

# 日志配置
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.yizhou.cloud: info
logstash:
  host: logstash